/*Troy - Simple Schema for a ticket. There are no declared fields for tickets,
as the autogenerated _id field is used when creating orders.

This is exportable so it can be used in other files. */
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const ticketSchema = new Schema({
});
const Ticket = mongoose.model("Ticket", ticketSchema);
module.exports = Ticket;
